### ISSUE TITLE
Reset the session once expired

### ISSUE THREAD

**Issue by tommaso-rossi** [watson-developer-cloud/assistant-simple#251] opened 2019-11-13 14:00 UTC
Hi, 
after the timeout limit, the ap.js file gives this error:
`http.onreadystatechange = function() {
      if (http.readyState === XMLHttpRequest.DONE && http.status === 200 && http.responseText) {
        Api.setResponsePayload(http.responseText);
      } else if (http.readyState === XMLHttpRequest.DONE && http.status !== 200) {
        Api.setErrorPayload({
          'output': {
            'generic': [
              {
                'response_type': 'text',
                'text': 'I\'m having trouble connecting to the server, please refresh the page'
              }
            ],
          }
        });
      }
    };`

And that's fine. Is there a way to automatically reload the session once we found that the session expired? Is there a simple way to call from there a sort of reloadSession() function?
Thank you

**Comment by Oliver-I** [comment] 2019-11-17 21:00
@tommaso-rossi You may be able to use the session_timeout value to create an automated session reload, as assistants can have differing expiration values.

In this case the demo is working as intended and I will close this issue.

Please note you can discuss development changes to your app at sources such as https://developer.ibm.com/answers/index.html.

**Closed by Oliver-I** 2019-11-17 21:01 UTC
